### ISSUE TITLE
Error in Mismatched [dir] && [lang] test

### ISSUE THREAD

**Issue by graymatter00** [lorenzodelijser/lintHTMLwithCSS.css#2]
LIne 188 currently reads...

`:is([lang="ar"], [lang="he"]):noet([dir="rtl"]),`

I believe the this should be the `:not` pseudo-class, instead of `:noet`.

**Comment by lorenzodelijser** [comment]
Thank you for your feedback I've addressed this issue in this commit: https://github.com/lorenzodelijser/lint-html-with-css/commit/2ad2395fb98a73050bba24501400256f944f1a3b
