### ISSUE TITLE
Error in  Only <li>'s allowed here!  test

### ISSUE THREAD

**Issue by graymatter00** [lorenzodelijser/lintHTMLwithCSS.css#3]
The `Only <li>'s allowed here!` test, starting at line 58, reads...

```
:is(ul, ol) *:not(li) {
    outline: var(--lint);
    content: "This selector hunts for lists that have something other than an <li> inside";
}
```

The first line, `:is(ul, ol) *:not(li)`, selects all child elements of the `ul` and `ol` elements.  This could include elements that are valid within an `li` element, such as images, inline SVGs, etc.

I suggest that the selector be changed so that only the immediate children of the `ul` and `ol` elements are selected.  Therefore...

`:is(ul, ol) > :not(li)`

**Comment by lorenzodelijser** [comment]
Thank you for your feedback I've addressed this issue in this commit: https://github.com/lorenzodelijser/lint-html-with-css/commit/3324ba02cdcc8caee6a1a77590b3a8751a7a411a
