### ISSUE TITLE
Duplicate tests

### ISSUE THREAD

**Issue by graymatter00** [lorenzodelijser/lintHTMLwithCSS.css#4]
There are two tests for `img` elements without `width` and `height` attributes.

Starting at line 66...

```
img:not([width]):not([height]) {
    outline: var(--lint);
    content: "Prevent page load jank and CLS by finding <img>'s missing height and width attributes";
}
```

And starting at line 262...

```
img:not([width]),
img:not([height]) {
    outline: var(--lint);
    content: "<img> without height and width that will cause cumulative layout shift. See: https://web.dev/optimize-cls/#images-without-dimensions";
}
```

I suggest removing the test that starts at line 66, as it will not select img elements that have a `width` attribute but do **not** have a `height` attribute.

**Comment by lorenzodelijser** [comment]
Thank you for your feedback I've addressed this issue in this commit: https://github.com/lorenzodelijser/lint-html-with-css/commit/8820b6125fabff9d28b69f48e0708f03d3e1dcc1
