### ISSUE TITLE
Some typos

### ISSUE THREAD

**Issue by graymatter00** [lorenzodelijser/lintHTMLwithCSS.css#5]
Line 7 and 13: lebels => labels

Line 21: parhaps => perhaps

Line 150 and 155: webp => WebP

Line 168 and 176: Geoffry => Geoffrey

**Comment by lorenzodelijser** [comment]
Thank you for your feedback I've addressed this issue in this commit: https://github.com/lorenzodelijser/lint-html-with-css/commit/9ed54c20a615c0e125a54431667dd28bfe89196f
