### ISSUE TITLE
Duplicate tests re: target="_blank"

### ISSUE THREAD

**Issue by graymatter00** [lorenzodelijser/lintHTMLwithCSS.css#6]
There are two tests for elements with the `target="_blank"` attribute but without appropriate `rel` attributes.

Starting at line 207...

```
[target$="blank"]:not(
    [rel],
    [rel*="noopener"],
    [rel*="noreferrer"]
) {
    outline: var(--lint);
    content: "Unsecure [target=blank]";
}
```
And starting at line 302...

```
a[target='_blank']:not([rel ='noopener']):not([rel='noreferrer']) {
    outline: var(--lint);
    content: "Prevent unsecure [target='_blank'] links";
}
```
I suggest removing the test that starts at line 302, as it will not select elements with `target="_blank"` that have a `rel ='noopener'` attribute but do **not** have a `rel='noreferrer'`attribute.

Additionally, both tests use the word **unsecure**.  Although sometimes used, apparently **unsecure** is not actually a word.  **Insecure** or **unsecured** should be used instead.  References below.

https://grammarhow.com/unsecure-vs-insecure/
https://english.stackexchange.com/questions/19653/insecure-or-unsecure-when-dealing-with-security

**Comment by lorenzodelijser** [comment]
Thank you for your feedback I've addressed this issue in this commit: https://github.com/lorenzodelijser/lint-html-with-css/commit/7c9e4a0be47882133f76931362c267777eab4b39
