### ISSUE TITLE
Error in attribute name

### ISSUE THREAD

**Issue by graymatter00** [lorenzodelijser/lintHTMLwithCSS.css#7]
There is an error in line 97.  It currently reads...

`:not([arialabelledby],[id]),`

It should read...

`:not([aria-labelledby],[id]),`

**Comment by lorenzodelijser** [comment]
Thank you for your feedback I've addressed this issue in this commit: https://github.com/lorenzodelijser/lint-html-with-css/commit/8f76b1791fb26c5626723133e5d90bcb5b1e17a6
